// AI attribution is recognized where it would enter a repository, and text
// that merely mentions AI is not mistaken for it.

import { describe, expect, test } from 'claude-code/testing'

import {
  addedAttribution,
  attributionInCommand,
  findAttribution,
  instructionFilesWritten,
  isInstructionFile,
  namesInstructionFile,
} from '../hooks/hygiene'

describe('attribution is recognized', () => {
  const TRAILERS: readonly string[] = [
    'Co-Authored-By: Claude <noreply@anthropic.com>',
    'Co-authored-by: Claude Opus 5.5 <noreply@anthropic.com>',
    'co-authored-by: ChatGPT <chatgpt@openai.com>',
    'Co-Authored-By: Codex <codex@openai.com>',
    'Co-authored-by: GitHub Copilot <copilot@github.com>',
    'Co-authored-by: Anthropic Claude <claude@example.com>',
    'Co-authored-by: AI Assistant <ai@example.com>',
    'Signed-off-by: Claude Code <noreply@anthropic.com>',
    '\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)',
    'Generated with Claude Code',
  ]
  for (const line of TRAILERS) {
    test(`trailer: ${line}`, () => {
      expect(findAttribution(`feat: add limiter\n\n${line}\n`)).toEqual([{ kind: 'trailer', line }])
    })
  }

  const PHRASES: readonly string[] = [
    'Generated by AI',
    'Built with Claude',
    'Written by ChatGPT',
    '// Generated by Copilot',
    '# This file was generated by Claude',
    '<!-- Created with the help of an AI assistant -->',
    'AI-generated',
    'Made with Codex',
  ]
  for (const line of PHRASES) {
    test(`phrase: ${line}`, () => {
      expect(findAttribution(line).map(one => one.kind)).toEqual(['phrase'])
    })
  }
})

describe('mentions of AI that are not attribution pass', () => {
  const FINE: readonly string[] = [
    'feat: cache AI-generated summaries for an hour',
    'Co-authored-by: Maria Souza <maria@example.com>',
    'Co-authored-by: Claude Dupont <claude.dupont@example.com>',
    'Co-authored-by: Devin Smith <devin@example.com>',
    'const label = "Generated by AI"',
    'return <Badge>Built with Claude</Badge>',
    'Add a client for the Anthropic API',
    'The summary is produced by the model and reviewed by a person before it ships to customers.',
    'fix: handle copilot seat sync failures',
    'docs: how to configure the Claude model id',
  ]
  for (const line of FINE) {
    test(line, () => {
      expect(findAttribution(line)).toEqual([])
    })
  }
})

describe('what an edit adds', () => {
  test('attribution already in the file is not the edit adding it', () => {
    const before = '# Notes\n\nBuilt with Claude\n'
    expect(addedAttribution(before, `${before}\nMore notes.\n`)).toEqual([])
  })

  test('a new line of it is', () => {
    expect(addedAttribution('# Notes\n', '# Notes\n\nGenerated by AI\n').map(one => one.line)).toEqual(['Generated by AI'])
  })
})

describe('commands that write to the repository', () => {
  test('a commit message in a here-document', () => {
    const command = "git commit -m \"$(cat <<'EOF'\nfeat: add limiter\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nEOF\n)\""
    expect(attributionInCommand(command).map(one => one.kind)).toEqual(['trailer'])
  })

  test('a trailer passed as its own -m', () => {
    const command = 'git add -A && git commit -m "feat: add limiter" -m "Co-authored-by: Codex <codex@openai.com>"'
    expect(attributionInCommand(command)).toHaveLength(1)
  })

  test('a trailer added with --trailer', () => {
    expect(attributionInCommand('git commit -m x --trailer "Co-authored-by: ChatGPT <c@openai.com>"')).toHaveLength(1)
  })

  test('a pull request body', () => {
    const command = 'gh pr create --title "Add limiter" --body "Adds a limiter.\n\n\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)"'
    expect(attributionInCommand(command)).toHaveLength(1)
  })

  test('a clean commit passes', () => {
    expect(attributionInCommand('git commit -m "feat: cache AI-generated summaries"')).toEqual([])
  })

  test('reading or searching for the same words writes nothing and passes', () => {
    expect(attributionInCommand('git log --grep="Co-authored-by: Claude"')).toEqual([])
    expect(attributionInCommand('grep -rn "Co-Authored-By: Claude" .')).toEqual([])
    expect(attributionInCommand('echo "Co-Authored-By: Claude <noreply@anthropic.com>"')).toEqual([])
  })
})

describe('instruction files', () => {
  test('are named CLAUDE.md and AGENTS.md, in any folder', () => {
    expect(isInstructionFile('/work/example/CLAUDE.md')).toBe(true)
    expect(isInstructionFile('packages/api/AGENTS.md')).toBe(true)
    expect(isInstructionFile('README.md')).toBe(false)
    expect(isInstructionFile('docs/claude.md.bak')).toBe(false)
  })

  test('a prompt that names one, or /init, is the person asking', () => {
    expect(namesInstructionFile('please write a CLAUDE.md for this repo')).toBe(true)
    expect(namesInstructionFile('add an agents.md')).toBe(true)
    expect(namesInstructionFile('/init')).toBe(true)
    expect(namesInstructionFile('fix the failing tests')).toBe(false)
  })

  test('are found when a shell command would write them', () => {
    expect(instructionFilesWritten('cat > CLAUDE.md <<EOF\n# Project\nEOF')).toEqual(['CLAUDE.md'])
    expect(instructionFilesWritten('touch AGENTS.md')).toEqual(['AGENTS.md'])
    expect(instructionFilesWritten('echo "# x" | tee docs/AGENTS.md')).toEqual(['docs/AGENTS.md'])
    expect(instructionFilesWritten('cp template.md CLAUDE.md')).toEqual(['CLAUDE.md'])
    expect(instructionFilesWritten('cat CLAUDE.md')).toEqual([])
    expect(instructionFilesWritten('cp CLAUDE.md /tmp/backup.md')).toEqual([])
  })
})
